-- ==========================================
-- 1. EXTENSIONS & ENUMS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_role AS ENUM ('student', 'instructor', 'admin');
CREATE TYPE license_type AS ENUM ('A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F');

-- ==========================================
-- 2. MODULE: TÀI KHOẢN & PHÂN QUYỀN
-- ==========================================
CREATE TABLE public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  role user_role default 'student'::user_role,
  target_license_type license_type,
  created_at timestamp with time zone default now()
);

-- Bật RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger: Tự động tạo profiles khi Signup Auth thành công
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 3. MODULE: HỌC TẬP (LÝ THUYẾT & MÔ PHỎNG)
-- ==========================================
CREATE TABLE public.theory_chapters (
  id integer primary key generated by default as identity,
  name text not null,
  description text
);

CREATE TABLE public.theory_questions (
  id integer primary key generated by default as identity,
  chapter_id integer references public.theory_chapters on delete cascade,
  content text not null,
  image_url text,
  is_critical boolean default false,
  options jsonb not null, -- VD: ["Dừng lại", "Đi tiếp", "Phanh"]
  correct_option integer not null, -- Chỉ số (0, 1, 2, 3) 
  explanation text
);

CREATE TABLE public.simulation_scenarios (
  id integer primary key generated by default as identity,
  title text not null,
  video_url text not null,
  perfect_time_start real not null,
  perfect_time_end real not null,
  description text
);

-- Public Read Only (Không yêu cầu Đăng nhập vẫn đọc được)
ALTER TABLE public.theory_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.theory_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_scenarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access" ON public.theory_chapters FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access" ON public.theory_questions FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access" ON public.simulation_scenarios FOR SELECT USING (true);

-- ==========================================
-- 4. MODULE: TIẾN TRÌNH CÁ NHÂN (TRACKING)
-- ==========================================
CREATE TABLE public.user_theory_answers (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  question_id integer references public.theory_questions(id) on delete cascade not null,
  is_correct boolean not null,
  updated_at timestamp with time zone default now()
);
-- Unique để người dùng không tạo nhiều row cho 1 câu hỏi
ALTER TABLE public.user_theory_answers ADD CONSTRAINT unique_user_question UNIQUE (user_id, question_id);

CREATE TABLE public.user_simulation_results (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  scenario_id integer references public.simulation_scenarios(id) on delete cascade not null,
  score integer not null check (score >= 0 and score <= 5),
  reaction_time real not null,
  created_at timestamp with time zone default now()
);

CREATE TABLE public.exam_histories (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  score integer not null,
  total_questions integer not null,
  is_passed boolean not null,
  time_taken_seconds integer not null,
  created_at timestamp with time zone default now()
);

-- Users can only modify and read their own progress
ALTER TABLE public.user_theory_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_simulation_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_histories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own answers" ON public.user_theory_answers FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users modify own answers" ON public.user_theory_answers FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users view own simulation results" ON public.user_simulation_results FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users modify own simulation results" ON public.user_simulation_results FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users view own exam histories" ON public.exam_histories FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users modify own exam histories" ON public.exam_histories FOR ALL USING (auth.uid() = user_id);

-- ==========================================
-- 5. MODULE: TRƯỜNG ĐÀO TẠO (MARKETPLACE)
-- ==========================================
CREATE TABLE public.driving_schools (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  address text,
  province text,
  price integer,
  rating_avg real default 0.0,
  total_reviews integer default 0
);

CREATE TABLE public.instructors (
  id uuid primary key default uuid_generate_v4(),
  school_id uuid references public.driving_schools(id) on delete set null,
  user_id uuid references public.profiles(id) on delete cascade,
  name text not null,
  years_of_experience integer,
  bio text
);

ALTER TABLE public.driving_schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.driving_schools FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.instructors FOR SELECT USING (true);

-- ==========================================
-- 6. MODULE: TRƯỜNG ĐÀO TẠO (MARKETPLACE & CỘNG ĐỒNG)
-- ==========================================
CREATE TABLE public.study_buddies (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade not null,
  location_area text not null,
  training_schedule text,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

CREATE TABLE public.forum_posts (
  id uuid primary key default uuid_generate_v4(),
  author_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  likes_count integer default 0,
  created_at timestamp with time zone default now()
);

CREATE TABLE public.forum_comments (
  id uuid primary key default uuid_generate_v4(),
  post_id uuid references public.forum_posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default now()
);

-- RLS Cộng đồng
ALTER TABLE public.study_buddies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read for buddies" ON public.study_buddies FOR SELECT USING (true);
CREATE POLICY "Own modify for buddies" ON public.study_buddies FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Public read for posts" ON public.forum_posts FOR SELECT USING (true);
CREATE POLICY "Auth users can insert posts" ON public.forum_posts FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Own modify for posts" ON public.forum_posts FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Own delete for posts" ON public.forum_posts FOR DELETE USING (auth.uid() = author_id);

CREATE POLICY "Public read for comments" ON public.forum_comments FOR SELECT USING (true);
CREATE POLICY "Auth users can insert comments" ON public.forum_comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Own modify for comments" ON public.forum_comments FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Own delete for comments" ON public.forum_comments FOR DELETE USING (auth.uid() = author_id);
